from setuptools import setup, find_packages

setup(
    name="visiontir",
    version="0.1.0",
    description="Vision and Thermal Infrared Analysis Package",
    author="Jorge Soler",
    author_email="",
    url="https://github.com/solerjorge/visiontir",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.20.0",
        "opencv-python>=4.5.0",
        "pillow>=8.0.0",
        "matplotlib>=3.3.0",
        "scipy>=1.6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.0",
            "pytest-cov>=2.11.0",
            "pytest-mock>=3.5.0",
            "black>=21.0",
            "flake8>=3.8.0",
            "pylint>=2.7.0",
            "mypy>=0.800",
            "sphinx>=3.5.0",
            "sphinx-rtd-theme>=0.5.0",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Image Processing",
        "Topic :: Scientific/Engineering :: Visualization",
    ],
)
